### ISSUE TITLE
Seemingly infinite loop somewhere

### ISSUE THREAD

**Issue by cfh294** [domlysz/Jenks-Caspall.py#1]
I've been using this script for an application, it works great. But for some reason, it seems to get hung up on a single list of values. 

This list: [3, 2, 17, 2, 6, 0, 10, 0, 7, 5, 7, 2, 5, 9, 5, 4, 5, 28, 16, 1, 1, 4, 1, 2, 2, 7, 29, 103, 16, 12, 9, 1, 14, 18, 2, 7, 5, 7, 13, 6, 4, 10, 6, 0, 2, 1, 3, 6] gets hung up when run with 4 breaks. 

I don't believe it's in my code as it works with all other datasets I'm using. It could be something with the calculation where for some reason it takes a very long time? 

I was wondering if you could run it on your end and see if you can replicate the behavior.

**Comment by domlysz** [comment]
Hi,

I have no problem with your list, bellow the test code

```python
from jenks_caspall import jenksCaspall

data = [3, 2, 17, 2, 6, 0, 10, 0, 7, 5, 7, 2, 5, 9, 5, 4, 5, 28, 16, 1, 1, 4, 1, 2, 2, 7, 29, 103, 16, 12, 9, 1, 14, 18, 2, 7, 5, 7, 13, 6, 4, 10, 6, 0, 2, 1, 3, 6]

clusters = jenksCaspall(data, k=4, nbAttempt=4, initStyle='kpp')
```

**Comment by cfh294** [comment]
Hm, it must be something on my end then. Thanks for testing it out. Your code was a big help to my department!

**Comment by domlysz** [comment]
I'm glad this code is useful for some !
